<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
		<AssemblyTitle>VitalShift</AssemblyTitle>
		<Product>VitalShift</Product>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="BoneLib">
		  <HintPath>$(HOME)/repos/BL-Libs/Mods/BoneLib.dll</HintPath>
		</Reference>
		<Reference Include="MelonLoader">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/net6/MelonLoader.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/Il2CppAssemblies/UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/Il2CppAssemblies/UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSLZ.Marrow">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/Il2CppAssemblies/Il2CppSLZ.Marrow.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/Il2CppAssemblies/Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppUniTask">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/Il2CppAssemblies/Il2CppUniTask.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/net6/Il2CppInterop.Runtime.dll</HintPath>
		</Reference>
	</ItemGroup>
	
	<ItemGroup>
		<Compile Include="VitalShift.cs"/>
	</ItemGroup>

	<Target Name="CopyOutput" AfterTargets="Build" Condition="'$(HOME)/repos/VitalShift/docs/Mods' != ''">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(HOME)/repos/VitalShift/docs/Mods"/>
	</Target>
</Project>
